[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'sonots/ctrlp.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

#[[plugins]] # TMUX
#repo = 'tmux-plugins/vim-tmux'
#on_ft = 'tmux'


